[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "HDM"
version = "0.0.1"
authors = [
  { name="Felix Risbro Hjerrild", email="felix+signDNE@hjerrild.org" },
  { name="Sofus Hesseldahl Laubel", email="sofus@laubel.net"}
]
description = "HDM description"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "GPL-3.0-or-later"
dependencies = ['scipy~=1.14.0', 'trimesh==4.6.8', 'numpy>=1.18', 'pyvista==0.45.0', 'scikit-learn==1.6.1', 'tqdm==4.67.1']


[project.urls]
Homepage = "https://github.com/frisbro303/HDM_Python"

[tool.setuptools.packages.find]
include = ["HDM*"]


[project.optional-dependencies]
dev = [
    "pytest>=8,<9",
    "psutil>=7,<8"
]